# Generated by Django 4.0.6 on 2022-07-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('fname_officer', models.CharField(max_length=50)),
                ('lname_officer', models.CharField(max_length=50)),
                ('election_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='election_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('fname_principal', models.CharField(max_length=50)),
                ('lname_principal', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
