# Generated by Django 4.0.6 on 2022-07-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_polling_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_election_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=30)),
                ('election_id', models.CharField(max_length=30)),
                ('active_poll_stations', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('students_voted', models.IntegerField()),
                ('students_pending', models.IntegerField()),
                ('polling_percentage', models.FloatField()),
            ],
        ),
    ]
