# Generated by Django 4.0.6 on 2022-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_current_election_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('adm_no', models.IntegerField()),
                ('apply_position', models.CharField(max_length=30)),
                ('position_id', models.CharField(max_length=10)),
            ],
        ),
    ]
