# Generated by Django 4.0.6 on 2022-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0007_election_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_posts',
            name='degree',
            field=models.CharField(choices=[('M', 'Mtech'), ('B', 'Btech'), ('All', 'All')], max_length=30),
        ),
        migrations.AlterField(
            model_name='election_posts',
            name='depts',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('EC', 'Electronics and Communications'), ('BT', 'Biotechnology'), ('ME', 'Mechanical'), ('P', 'Production'), ('All', 'All')], max_length=30),
        ),
        migrations.AlterField(
            model_name='election_posts',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('All', 'All')], max_length=30),
        ),
        migrations.AlterField(
            model_name='election_posts',
            name='year',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('All', 'All')], max_length=30),
        ),
    ]
