# Generated by Django 4.0.6 on 2022-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0008_alter_election_posts_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polling_station',
            name='n_nodes',
            field=models.IntegerField(null=True),
        ),
    ]
