# Generated by Django 4.0.6 on 2022-07-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('adm_no', models.IntegerField()),
                ('department', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
