# Generated by Django 4.0.6 on 2022-07-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
